version: '2.1'

volumes:
  db-data:
  vendor:
  var:

services:
  mysql:
    image: mysql:5.6
    ports:
      - "3306"
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: prestashop
      MYSQL_DATABASE: prestashop
    restart: always
    networks:
      - traefik-public
    
  prestashop:
    build:
      context: .
      dockerfile: .docker/Dockerfile
      args:
        - PS_VERSION_DF=${PS_VERSION_DF} #Used in dockerfile
    environment:
      PS_VERSION: ${PS_VERSION} 
      MOLLIE_VERSION: ${MOLLIE_VERSION} 
      DB_PASSWD: ${DB_PASSWD}
      DB_NAME: ${DB_NAME}
      DB_SERVER: ${DB_SERVER}
      DB_PREFIX: ${DB_PREFIX}
      PS_INSTALL_AUTO: ${PS_INSTALL_AUTO}
      PS_DOMAIN: ${PS_DOMAIN}
      PS_FOLDER_INSTALL: ${PS_FOLDER_INSTALL}
      PS_FOLDER_ADMIN: ${PS_FOLDER_ADMIN}
      PS_COUNTRY: ${PS_COUNTRY}
      PS_LANGUAGE: ${PS_LANGUAGE}
      PS_DEV_MODE: ${PS_DEV_MODE}
      ADMIN_PASSWD: ${ADMIN_PASSWD}
    command: ["/tmp/wait-for-it.sh", "--timeout=60", "--strict", "mysql:3306", "--", "/tmp/docker_run_git.sh"]
    ports:
      - "8001:80"
    volumes:
      - ./:/var/www/html:delegated
    networks:
      - traefik-public

networks:
    traefik-public:
        name: traefik-public